[theme]
primaryColor = "#BB86FC"      # Violet clair
backgroundColor = "#202124"   # Noir/gris foncé
secondaryBackgroundColor = "#292A2D"  # Gris métallique
textColor = "#E0E0E0"         # Gris clair
font = "sans serif"
