[theme]
primaryColor = "#4A90E2"      # Bleu vif
backgroundColor = "#0B1A30"   # Bleu marine très foncé
secondaryBackgroundColor = "#172A45"  # Bleu-gris foncé
textColor = "#F1F1F1"         # Blanc clair
font = "serif"
