[theme]
primaryColor = "#00FFC6"      # Vert néon
backgroundColor = "#121212"   # Noir/gris sombre
secondaryBackgroundColor = "#1F1F1F"  # Gris très foncé
textColor = "#E8E8E8"         # Blanc cassé
font = "sans serif"
