[theme]
primaryColor = "#BB86FC"      # Violet clair
backgroundColor = "#121212"   # Noir/gris très sombre
secondaryBackgroundColor = "#1F1F1F"  # Gris foncé
textColor = "#E0E0E0"         # Blanc/gris clair
font = "sans serif"

